#pragma once

#include "StdAfx.h"

#define SITE_COUNT 1

FPVI10 VM(0, "VM");
FPVI10 AISEN(1, "AISEN");
FPVI10 AOUT1(2, "AOUT1");
FPVI10 AOUT2(3, "AOUT2");

FOVI nSLEEP(0, "nSLEEP");
FOVI nFAULT(1, "nFAULT");
FOVI BISEN(2, "BISEN");
FOVI BOUT2(3, "BOUT2");

FOVI BOUT1(4, "BOUT1");
FOVI BIN1(5, "BIN1");
FOVI BIN2(6, "BIN2");
FOVI VREF(7, "VREF");

FOVI VINT(8, "VINT");
FOVI AIN2(9, "AIN2");
FOVI AIN1(10, "AIN1");

QTMU_PLUS qtmu0(0, "qtmu0");
QTMU_PLUS qtmu1(1, "qtmu1");
QTMU_PLUS qtmu2(2, "qtmu2");